language: node_js
node_js:
  - "4.0"
  - "4.2"
  - "5.0"
  - "5.1"
  - "stable"
before_install:
script: "npm run-script test-travis"
# Send coverage data to Coveralls
before_script:
after_script: "npm run-script coverall"
